import prisma from '@/lib/prisma';
import { ProjectsPage } from '@/modules/projects';
import { Project } from '@prisma/client';
import { GetServerSideProps } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';

interface Props {
  projects: Project[];
}

export default function Home({ projects }: Props) {
  const router = useRouter();

  const refreshData = () => {
    router.replace(router.asPath);
  };
  return (
    <>
      <Head>
        <title>Task Planner</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <ProjectsPage projects={projects} refreshData={refreshData} />
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async () => {
  const projects = await prisma.project.findMany();
  return {
    props: { projects },
  };
};
